### ISSUE TITLE
Use the transmitter of the controller via USB

### ISSUE THREAD

**Issue by gonsp** [kingkong-rc/TINY-TX-X8#15]
Hi!

For a hackathon project I'm interested in using the controller just as a transmitter, and send from my PC via USB the values for each channel to the controller, instead of using the joysticks.

So I could write a program for my PC that controls the drone. Does anyone have some suggestions? Or is there something similar already implemented?

Thanks!

**Comment by KaitlynSeU** [comment]
Sorry, X8/X8M use a USB to UART Bridge chip, you can't make it as a joysticks

**Comment by gonsp** [comment]
We actually accomplished it. If anyone is interested in this, reopen this issue.

**Comment by photomatt74** [comment]
Yes, I'm very interested. This is a great controller for high school STEM projects. It would be great if they could fly a simulator before they crash any tiny whoops. Thanks for your efforts!

**Comment by okalachev** [comment]
Hey, I wrote a Python script to parse this transmitter data from USB: https://gist.github.com/okalachev/7704b15c7d0752acad72e50a35a460b1.

@photomatt74, maybe you're still interested.
